language: java
before_install: 
  - nvm install 12.0
  - cd ./front-end
  - npm install
  - npm run build
before_script:
  - cp -R ./front-end/build/ ./backend/src/main/resources/static/
  - cd ./backend
script: mvn package -DskipTests



